import type { L10n } from '../i18n/utils';

export type Element = 'Earth' | 'Wind' | 'Fire' | 'Light' | 'Shadow';
export type Tier = 'S' | 'A' | 'B' | 'C';

export interface Hero {
  slug: string;
  name: string;
  role: L10n<string>;
  tier: Tier;
  element: Element;
  lead: L10n<string>; // short tagline
  bio: L10n<string>;
  bestBeast: L10n<string>;
  tip: L10n<string>;
}

export const HEROES: Hero[] = [
  {
    slug: 'aurelia',
    name: 'Aurelia',
    role: {
      en: 'Infantry Commander',
      fr: 'Commandante d’infanterie',
      de: 'Infanterie-Kommandantin',
      es: 'Comandante de infantería',
      it: 'Comandante di fanteria',
    },
    tier: 'S',
    element: 'Light',
    lead: {
      en: 'The shield wall that never breaks.',
      fr: 'Le mur de boucliers qui ne se brise jamais.',
      de: 'Die Schildmauer, die niemals bricht.',
      es: 'El muro de escudos que nunca se rompe.',
      it: 'La barriera di scudi che non si spezza mai.',
    },
    bio: {
      en: 'Aurelia turns a frightened levy into a living wall. Her shield scales with garrison size, so she gets stronger the more you invest in the Stead.',
      fr: 'Aurelia transforme une levée effrayée en un mur vivant. Son bouclier scale avec la taille de la garnison, donc elle se renforce plus vous investissez dans la Stead.',
      de: 'Aurelia verwandelt eine verängstigte Miliz in eine lebende Mauer. Ihr Schild skaliert mit der Garnisonsgröße, also wird sie stärker, je mehr ihr in die Stead investiert.',
      es: 'Aurelia convierte una leva asustada en un muro viviente. Su escudo escala con el tamaño de la guarnición, así que se vuelve más fuerte cuanto más inviertes en la Stead.',
      it: 'Aurelia trasforma una leva spaventata in un muro vivente. Il suo scudo scala con la dimensione della guarnigione, quindi diventa più forte quanto più investi nella Stead.',
    },
    bestBeast: { en: 'Greywood Stag' },
    tip: {
      en: 'Front-load garrison buildings; her value is multiplicative with population.',
      fr: 'Construisez les bâtiments de garnison en premier ; sa valeur est multiplicative avec la population.',
      de: 'Baut Garnisonsgebäude zuerst; ihr Wert ist multiplikativ mit der Bevölkerung.',
      es: 'Prioriza los edificios de guarnición; su valor es multiplicativo con la población.',
      it: 'Costruisci prima gli edifici della guarnigione; il suo valore è moltiplicativo con la popolazione.',
    },
  },
  {
    slug: 'drusus',
    name: 'Drusus',
    role: {
      en: 'Cavalry Commander',
      fr: 'Commandant de cavalerie',
      de: 'Kavallerie-Kommandant',
      es: 'Comandante de caballería',
      it: 'Comandante di cavalleria',
    },
    tier: 'S',
    element: 'Fire',
    lead: {
      en: 'The rally leader who burns the line.',
      fr: 'Le meneur de rally qui brûle la ligne.',
      de: 'Der Rally-Anführer, der die Linie brennt.',
      es: 'El líder de rally que quema la línea.',
      it: 'Il leader di rally che brucia la linea.',
    },
    bio: {
      en: 'Drusus leads the border-raid rally better than anyone. Pair him with Octavia to stack burn, then execute for bonus damage on low HP.',
      fr: 'Drusus mène le rally de border raid mieux que quiconque. Associez-le à Octavia pour empiler les brûlures, puis exécutez pour des dégâts bonus sur PV faibles.',
      de: 'Drusus führt den Grenzraid-Rally besser als jeder andere. Kombiniert ihn mit Octavia, um Brennen zu stapeln, und führt dann Execute für Bonusschaden bei niedrigem HP aus.',
      es: 'Drusus lidera el rally de incursión fronteriza mejor que nadie. Combínalo con Octavia para apilar quemaduras y luego ejecuta para daño bonus con HP bajo.',
      it: 'Drusus guida il rally di incursione di confine meglio di chiunque altro. Abbinalo a Octavia per impilare bruciature, poi esegui per danni bonus con HP bassi.',
    },
    bestBeast: { en: 'Verge Wyrm' },
    tip: {
      en: 'Always lead the rally with Drusus + Octavia in the same march.',
      fr: 'Menez toujours le rally avec Drusus + Octavia dans la même marche.',
      de: 'Führt das Rally immer mit Drusus + Octavia im selben Marsch an.',
      es: 'Lidera siempre el rally con Drusus + Octavia en la misma marcha.',
      it: 'Guida sempre il rally con Drusus + Octavia nella stessa marcia.',
    },
  },
  {
    slug: 'octavia',
    name: 'Octavia',
    role: {
      en: 'Marksman',
      fr: 'Tireuse d’élite',
      de: 'Schützin',
      es: 'Francotiradora',
      it: 'Cecchina',
    },
    tier: 'S',
    element: 'Shadow',
    lead: {
      en: 'One arrow. One corpse.',
      fr: 'Une flèche. Un cadavre.',
      de: 'Ein Pfeil. Eine Leiche.',
      es: 'Una flecha. Un cadáver.',
      it: 'Una freccia. Un cadavere.',
    },
    bio: {
      en: 'Octavia deletes single targets. She struggles against spread formations but is the best boss-and-rally finisher in the game.',
      fr: 'Octavia supprime les cibles uniques. Elle peine contre les formations étalées mais est la meilleure finisseuse de boss et de rally du jeu.',
      de: 'Octavia löscht Einzelziele. Sie kämpft gegen verteilte Formationen, ist aber die beste Boss- und Rally-Bezwingerin im Spiel.',
      es: 'Octavia elimina objetivos únicos. Sufre contra formaciones dispersas, pero es la mejor rematadora de jefes y rally del juego.',
      it: 'Octavia elimina bersagli singoli. Fatica contro le formazioni sparse, ma è la migliore finitrice di boss e rally del gioco.',
    },
    bestBeast: { en: 'Verge Hound' },
    tip: {
      en: 'Save her for the execute window; never open with her into a swarm.',
      fr: 'Gardez-la pour la fenêtre d’exécution ; n’ouvrez jamais avec elle face à un swarm.',
      de: 'Spart sie für das Execute-Fenster auf; eröffnet nie mit ihr gegen einen Schwarm.',
      es: 'Resérvala para la ventana de ejecución; nunca abras con ella contra un swarm.',
      it: 'Riservala per la finestra di esecuzione; non aprire mai con lei contro uno swarm.',
    },
  },
  {
    slug: 'titus',
    name: 'Titus',
    role: {
      en: 'Infantry Commander',
      fr: 'Commandant d’infanterie',
      de: 'Infanterie-Kommandant',
      es: 'Comandante de infantería',
      it: 'Comandante di fanteria',
    },
    tier: 'A',
    element: 'Earth',
    lead: {
      en: 'The reliable wall.',
      fr: 'Le mur fiable.',
      de: 'Die verlässliche Mauer.',
      es: 'El muro fiable.',
      it: 'Il muro affidabile.',
    },
    bio: {
      en: 'Titus is the budget Aurelia — superb early game and a faction-boss tank you will use for months.',
      fr: 'Titus est l’Aurelia low-cost — excellent early game et tanque de boss de faction que vous utiliserez des mois.',
      de: 'Titus ist die günstige Aurelia — exzellent im frühen Spiel und ein Fraktionsboss-Tank, den ihr monatelang nutzt.',
      es: 'Titus es la Aurelia de presupuesto — excelente en early game y tanque de jefe de facción que usarás por meses.',
      it: 'Titus è l’Aurelia economica — ottimo nelle fasi iniziali e un tank per boss di fazione che userai per mesi.',
    },
    bestBeast: { en: 'Greywood Stag' },
    tip: {
      en: 'Your first 5-star; do not skip him for shinier S-tier.',
      fr: 'Votre premier 5 étoiles ; ne le sautez pas pour un S-tier plus brillant.',
      de: 'Euer erster 5-Sterne; überspringt ihn nicht für einen glänzenderen S-Tier.',
      es: 'Tu primer 5 estrellas; no lo saltes por un S-tier más brillante.',
      it: 'Il tuo primo 5 stelle; non saltarlo per un S-tier più luccicante.',
    },
  },
  {
    slug: 'cornelia',
    name: 'Cornelia',
    role: {
      en: 'Marksman',
      fr: 'Tireuse d’élite',
      de: 'Schützin',
      es: 'Francotiradora',
      it: 'Cecchina',
    },
    tier: 'A',
    element: 'Wind',
    lead: {
      en: 'Wind that clears the swarm.',
      fr: 'Le vent qui nettoie le swarm.',
      de: 'Wind, der den Schwarm fegt.',
      es: 'Viento que barre el swarm.',
      it: 'Vento che spazza lo swarm.',
    },
    bio: {
      en: 'Cornelia’s AoE outshines Octavia on beast hunts and swarm content where single-target falls flat.',
      fr: 'L’AoE de Cornelia surpasse Octavia sur les chasses de bêtes et le contenu swarm où la cible unique échoue.',
      de: 'Cornelias AoE überstrahlt Octavia bei Bestienjagden und Schwarm-Inhalten, wo Einzelziel flach fällt.',
      es: 'El AoE de Cornelia supera a Octavia en cacerías de bestias y contenido swarm donde el objetivo único falla.',
      it: 'L’AoE di Cornelia supera Octavia nelle cacce alle bestie e nei contenuti swarm dove il bersaglio singolo cade in piano.',
    },
    bestBeast: { en: 'Verge Hound' },
    tip: {
      en: 'Swap to Cornelia whenever the enemy comes in numbers.',
      fr: 'Passez à Cornelia dès que l’ennemi arrive en nombre.',
      de: 'Wechselt zu Cornelia, sobald der Feind in Massen kommt.',
      es: 'Cambia a Cornelia cuando el enemigo viene en número.',
      it: 'Passa a Cornelia ogni volta che il nemico arriva in massa.',
    },
  },
  {
    slug: 'maximus',
    name: 'Maximus',
    role: {
      en: 'Cavalry Commander',
      fr: 'Commandant de cavalerie',
      de: 'Kavallerie-Kommandant',
      es: 'Comandante de caballería',
      it: 'Comandante di cavalleria',
    },
    tier: 'A',
    element: 'Light',
    lead: {
      en: 'The Frost-counter flank.',
      fr: 'Le flanc anti-Frost.',
      de: 'Der Frost-Konter-Flank.',
      es: 'El flanco anti-Frost.',
      it: 'Il fianco anti-Frost.',
    },
    bio: {
      en: 'Maximus hard-counters Frost Confederacy cavalry with a light-charged flank that ignores their slow.',
      fr: 'Maximus hard-counter la cavalerie de la Frost Confederacy avec un flanc chargé de lumière qui ignore leur lent.',
      de: 'Maximus kontert die Kavallerie der Frost Confederacy hart mit einem licht-aufgeladenen Flank, der deren Verlangsamung ignoriert.',
      es: 'Maximus hace hard-counter a la caballería de la Frost Confederacy con un flanco cargado de luz que ignora su lentitud.',
      it: 'Maximus hard-countera la cavalleria della Frost Confederacy con un fianco carico di luce che ignora la loro lentezza.',
    },
    bestBeast: { en: 'Verge Wyrm' },
    tip: {
      en: 'Deploy him specifically against Frost PvP marches.',
      fr: 'Déployez-le spécifiquement contre les marches PvP Frost.',
      de: 'Setzt ihn gezielt gegen Frost-PvP-Märsche ein.',
      es: 'Despliégalo específicamente contra las marchas PvP Frost.',
      it: 'Schiera lui specificamente contro le marce PvP Frost.',
    },
  },
  {
    slug: 'lucia',
    name: 'Lucia',
    role: {
      en: 'Infantry Commander',
      fr: 'Commandant d’infanterie',
      de: 'Infanterie-Kommandantin',
      es: 'Comandante de infantería',
      it: 'Comandante di fanteria',
    },
    tier: 'B',
    element: 'Earth',
    lead: {
      en: 'Steady and cheap.',
      fr: 'Stable et pas chère.',
      de: 'Beständig und günstig.',
      es: 'Firme y barata.',
      it: 'Sicura ed economica.',
    },
    bio: {
      en: 'Lucia is the free starter infantry. She carries you to your first S-tier pull and then retires gracefully.',
      fr: 'Lucia est l’infanterie de départ gratuite. Elle vous porte jusqu’à votre premier tirage S-tier puis prend sa retraite avec grâce.',
      de: 'Lucia ist die kostenlose Starter-Infanterie. Sie trägt euch bis zu eurem ersten S-Tier-Zug und geht dann elegant in Rente.',
      es: 'Lucia es la infantería inicial gratuita. Te lleva hasta tu primer gachapon S-tier y luego se retira con gracia.',
      it: 'Lucia è la fanteria iniziale gratuita. Ti porta alla tua prima estrazione S-tier e poi si ritira con grazia.',
    },
    bestBeast: { en: 'Verge Hound' },
    tip: {
      en: 'Train her only to unlock the infantry tree.',
      fr: 'Entraînez-la uniquement pour débloquer l’arbre d’infanterie.',
      de: 'Trainiert sie nur, um den Infanterie-Baum freizuschalten.',
      es: 'Entrénarla solo para desbloquear el árbol de infantería.',
      it: 'Addestrala solo per sbloccare l’albero della fanteria.',
    },
  },
  {
    slug: 'brutus',
    name: 'Brutus',
    role: {
      en: 'Cavalry Commander',
      fr: 'Commandant de cavalerie',
      de: 'Kavallerie-Kommandant',
      es: 'Comandante de caballería',
      it: 'Comandante di cavalleria',
    },
    tier: 'B',
    element: 'Fire',
    lead: {
      en: 'Burst, then gone.',
      fr: 'Burst, puis disparu.',
      de: 'Burst, dann weg.',
      es: 'Burst, y se fue.',
      it: 'Burst, poi sparito.',
    },
    bio: {
      en: 'Brutus trades durability for a one-time fire burst. Fun, but outclassed by Drusus in every raid.',
      fr: 'Brutus échange la durabilité contre un burst de feu unique. Amusant, mais surpassé par Drusus dans chaque raid.',
      de: 'Brutus tauscht Haltbarkeit gegen einen einmaligen Feuer-Burst. Spaß, aber in jedem Raid von Drusus übertroffen.',
      es: 'Brutus cambia durabilidad por un burst de fuego único. Divertido, pero superado por Drusus en cada incursión.',
      it: 'Brutus scambia la durabilità per un burst di fuoco singolo. Divertente, ma superato da Drusus in ogni raid.',
    },
    bestBeast: { en: 'Verge Wyrm' },
    tip: {
      en: 'Use him only if Drusus is unavailable.',
      fr: 'Utilisez-le seulement si Drusus est indisponible.',
      de: 'Nutzt ihn nur, wenn Drusus nicht verfügbar ist.',
      es: 'Úsalo solo si Drusus no está disponible.',
      it: 'Usalo solo se Drusus non è disponibile.',
    },
  },
  {
    slug: 'servilia',
    name: 'Servilia',
    role: {
      en: 'Marksman',
      fr: 'Tireuse d’élite',
      de: 'Schützin',
      es: 'Francotiradora',
      it: 'Cecchina',
    },
    tier: 'C',
    element: 'Wind',
    lead: {
      en: 'Training wheels.',
      fr: 'Roues d’apprentissage.',
      de: 'Trainingsräder.',
      es: 'Ruedas de entrenamiento.',
      it: 'Ruote di allenamento.',
    },
    bio: {
      en: 'Servilia is the starter marksman. Keep her for the collection and move to Cornelia fast.',
      fr: 'Servilia est la tireuse d’élite de départ. Gardez-la pour la collection et passez vite à Cornelia.',
      de: 'Servilia ist die Starter-Schützin. Behaltet sie für die Sammlung und wechselt schnell zu Cornelia.',
      es: 'Servilia es la francotiradora inicial. Consérvala para la colección y pasa pronto a Cornelia.',
      it: 'Servilia è la cecchina iniziale. Tienila per la collezione e passa presto a Cornelia.',
    },
    bestBeast: { en: 'Verge Hound' },
    tip: {
      en: 'Do not invest resources; she is a placeholder.',
      fr: 'N’investissez pas de ressources ; c’est un placeholder.',
      de: 'Investiert keine Ressourcen; sie ist ein Platzhalter.',
      es: 'No inviertas recursos; es un placeholder.',
      it: 'Non investire risorse; è un placeholder.',
    },
  },
  {
    slug: 'decimus',
    name: 'Decimus',
    role: {
      en: 'Infantry Commander',
      fr: 'Commandant d’infanterie',
      de: 'Infanterie-Kommandant',
      es: 'Comandante de infantería',
      it: 'Comandante di fanteria',
    },
    tier: 'C',
    element: 'Shadow',
    lead: {
      en: 'A shadow of better men.',
      fr: 'L’ombre d’hommes meilleurs.',
      de: 'Ein Schatten besserer Männer.',
      es: 'La sombra de hombres mejores.',
      it: 'L’ombra di uomini migliori.',
    },
    bio: {
      en: 'Decimus is a shadow-element infuser with no standout stat. Skip unless you collect them all.',
      fr: 'Decimus est un infuseur d’élément ombre sans statistique marquante. À skip sauf si vous les collectez tous.',
      de: 'Decimus ist ein Schatten-Element-Verstärker ohne herausragende Stat. Überspringen, es sei denn ihr sammelt sie alle.',
      es: 'Decimus es un infusor de elemento sombra sin una stat destacada. Salta a menos que los colecciones todos.',
      it: 'Decimus è un infusore di elemento ombra senza statistiche di rilievo. Salta a meno che non li collezioni tutti.',
    },
    bestBeast: { en: 'Greywood Stag' },
    tip: {
      en: 'Fodder for hero upgrades.',
      fr: 'Fodder pour les améliorations de héros.',
      de: 'Futter für Helden-Upgrades.',
      es: 'Forraje para mejoras de héroes.',
      it: 'Foraggio per i potenziamenti degli eroi.',
    },
  },
  {
    slug: 'pomponia',
    name: 'Pomponia',
    role: {
      en: 'Cavalry Commander',
      fr: 'Commandant de cavalerie',
      de: 'Kavallerie-Kommandantin',
      es: 'Comandante de caballería',
      it: 'Comandante di cavalleria',
    },
    tier: 'C',
    element: 'Light',
    lead: {
      en: 'Bright, but shallow.',
      fr: 'Brillante, mais superficielle.',
      de: 'Hell, aber flach.',
      es: 'Brillante, pero superficial.',
      it: 'Luminosa, ma superficiale.',
    },
    bio: {
      en: 'Pomponia shines in the tutorial and nowhere else. A light-cavalry intro unit.',
      fr: 'Pomponia brille dans le tutoriel et nulle part ailleurs. Une unité d’intro de cavalerie légère.',
      de: 'Pomponia glänzt im Tutorial und sonst nirgends. Eine leichte Kavallerie-Intro-Einheit.',
      es: 'Pomponia brilla en el tutorial y en ningún otro sitio. Una unidad intro de caballería ligera.',
      it: 'Pomponia brilla nel tutorial e in nessun altro luogo. Un’unità introduttiva di cavalleria leggera.',
    },
    bestBeast: { en: 'Verge Hound' },
    tip: {
      en: 'Retire after day 3.',
      fr: 'À retirer après le jour 3.',
      de: 'Nach Tag 3 in Rente schicken.',
      es: 'Retírala después del día 3.',
      it: 'Da ritirare dopo il giorno 3.',
    },
  },
];

export function getHero(slug: string): Hero | undefined {
  return HEROES.find((h) => h.slug === slug);
}
