// Generated by scripts/gen-image-dims.mjs — the IMAGE_DIMS table is regenerated,
// but mediaProps/dims below are hand-written; keep them when regenerating.
// Intrinsic pixel size of every image under public/media, used to set
// width/height on <img> so the browser can reserve space (no CLS).

import { media } from '../i18n/utils';

export const IMAGE_DIMS: Record<string, { width: number; height: number }> = {
  'logos/brand-colour.png': { width: 900, height: 196 },
  'logos/romestead-logo.png': { width: 400, height: 87 },
  'screens/altar.jpg': { width: 1280, height: 720 },
  'screens/community.jpg': { width: 1280, height: 720 },
  'screens/construct-sites.jpg': { width: 1280, height: 720 },
  'screens/desert-poi.jpg': { width: 1280, height: 720 },
  'screens/desert-town-2.jpg': { width: 1280, height: 720 },
  'screens/desert-town.png': { width: 1280, height: 720 },
  'screens/desert-town.webp': { width: 1280, height: 720 },
  'screens/desert.jpg': { width: 1280, height: 720 },
  'screens/dungeon.jpg': { width: 1280, height: 720 },
  'screens/fight-cyclops.png': { width: 1280, height: 720 },
  'screens/fight-cyclops.webp': { width: 1280, height: 720 },
  'screens/fight-pyzifax.png': { width: 1280, height: 720 },
  'screens/fight-pyzifax.webp': { width: 1280, height: 720 },
  'screens/forest-combat.jpg': { width: 1280, height: 720 },
  'screens/forest-raid.png': { width: 1280, height: 720 },
  'screens/forest-raid.webp': { width: 1280, height: 720 },
  'screens/owl-1.jpg': { width: 1280, height: 720 },
  'screens/owl-fight.jpg': { width: 1280, height: 720 },
  'screens/owl.jpg': { width: 1280, height: 720 },
  'screens/phoenix-fight.jpg': { width: 1280, height: 720 },
  'screens/shot3.jpg': { width: 1280, height: 720 },
  'screens/shot4.png': { width: 1280, height: 720 },
  'screens/town-nice.jpg': { width: 1280, height: 720 },
  'screens/town-start.png': { width: 1280, height: 720 },
  'screens/town-start.webp': { width: 1280, height: 720 },
  'screens/ui.jpg': { width: 1280, height: 720 },
  'screens/ui.webp': { width: 1280, height: 720 },
  'screens/volcanic-tendril.jpg': { width: 1280, height: 720 },
  'screens/volcano-poi.png': { width: 1280, height: 720 },
  'screens/volcano-poi.webp': { width: 1280, height: 720 },
  'screens/woods-night.jpg': { width: 1280, height: 720 },
};

export function dims(src: string): { width: number; height: number } | undefined {
  return IMAGE_DIMS[src];
}

// NOTE: keep the media() import below the table so the generated header stays obvious.

/**
 * Spread onto an <img>: emits src + intrinsic width/height so the browser can
 * reserve layout space (prevents CLS). Falls back to src-only when unknown.
 */
export function mediaProps(p: string): { src: string; width?: number; height?: number } {
  const d = IMAGE_DIMS[p];
  return d ? { src: media(p), width: d.width, height: d.height } : { src: media(p) };
}
