// One-off: insert bestiary + worship UI keys into each locale block of ui.ts.
// Anchors: the unique footer.built sentence of each language.
import fs from 'node:fs';

const path = 'C:/Users/Administrator/WorkBuddy/Claw/romestead-astro/src/i18n/ui.ts';
let raw = fs.readFileSync(path, 'utf8');
const ap = '\u2019'; // typographic apostrophe, consistent with the rest of the file

const blocks = {
  en: {
    anchor: "written and kept up to date by a small crew of governors",
    keys: [
      `    'nav.bestiary': 'Bestiary',`,
      `    'bestiary.title': 'Bestiary ${ap} Enemies & Drops',`,
      `    'bestiary.intro': 'Every creature on record: HP, drops and where they appear. Cross-checked against the community wiki.',`,
      `    'bestiary.name': 'Creature',`,
      `    'bestiary.kind': 'Type',`,
      `    'bestiary.hp': 'HP',`,
      `    'bestiary.drops': 'Drops',`,
      `    'bestiary.notes': 'Notes',`,
      `    'bestiary.hostile': 'Hostile',`,
      `    'bestiary.passive': 'Passive',`,
      `    'bestiary.group.anywhere': 'Anywhere (raids & night)',`,
      `    'bestiary.group.plains': 'Plains',`,
      `    'bestiary.group.forest': 'Forest',`,
      `    'bestiary.group.desert': 'Desert',`,
      `    'bestiary.group.volcano': 'Volcano',`,
      `    'worship.title': 'Worship tech tree',`,
      `    'worship.intro': 'Spend Worship Points earned from altar offerings to unlock nodes, tier by tier.',`,
      `    'worship.tier': 'Tier',`,
      `    'worship.node': 'Node',`,
      `    'worship.effect': 'Effect',`,
      `    'worship.cost': 'Cost',`,
      `    'worship.prereq': 'Requires',`,
      `    'worship.wp': 'WP',`,
      `    'minerva.quests.title': 'Minerva${ap}s quest chain',`,
      `    'minerva.quests.intro': 'Minerva grants no worship tree ${ap} her power returns through quests. Offer these items at your Altar.',`,
      `    'minerva.quests.offer': 'Offer at the altar',`,
      `    'minerva.quests.reward': 'Reward',`,
    ],
  },
  fr: {
    anchor: "r\u00e9dig\u00e9 et tenu \u00e0 jour par un petit groupe de gouverneurs",
    keys: [
      `    'nav.bestiary': 'Bestiaire',`,
      `    'bestiary.title': 'Bestiaire ${ap} Ennemis & butins',`,
      `    'bestiary.intro': 'Toutes les cr\u00e9atures r\u00e9pertori\u00e9es : PV, butins et lieux d${ap}apparition. Donn\u00e9es v\u00e9rifi\u00e9es avec le wiki communautaire.',`,
      `    'bestiary.name': 'Cr\u00e9ature',`,
      `    'bestiary.kind': 'Type',`,
      `    'bestiary.hp': 'PV',`,
      `    'bestiary.drops': 'Butins',`,
      `    'bestiary.notes': 'Notes',`,
      `    'bestiary.hostile': 'Hostile',`,
      `    'bestiary.passive': 'Passive',`,
      `    'bestiary.group.anywhere': 'Partout (raids & nuit)',`,
      `    'bestiary.group.plains': 'Plaines',`,
      `    'bestiary.group.forest': 'For\u00eats',`,
      `    'bestiary.group.desert': 'D\u00e9sert',`,
      `    'bestiary.group.volcano': 'Volcan',`,
      `    'worship.title': 'Arbre de culte',`,
      `    'worship.intro': 'D\u00e9pensez les Points de Culte gagn\u00e9s par les offrandes ${ap} l${ap}autel pour d\u00e9bloquer les n\u0153uds, palier par palier.',`,
      `    'worship.tier': 'Palier',`,
      `    'worship.node': 'N\u0153ud',`,
      `    'worship.effect': 'Effet',`,
      `    'worship.cost': 'Co\u00fbt',`,
      `    'worship.prereq': 'Pr\u00e9requis',`,
      `    'worship.wp': 'PC',`,
      `    'minerva.quests.title': 'Cha\u00eene de qu\u00eates de Minerve',`,
      `    'minerva.quests.intro': 'Minerve n${ap}a pas d${ap}arbre de culte ${ap} son pouvoir revient par les qu\u00eates. Offrez ces objets ${ap} votre Autel.',`,
      `    'minerva.quests.offer': 'Offrir ${ap} l${ap}autel',`,
      `    'minerva.quests.reward': 'R\u00e9compense',`,
    ],
  },
  de: {
    anchor: "geschrieben und aktuell gehalten von einer kleinen Gruppe Governors",
    keys: [
      `    'nav.bestiary': 'Bestiarium',`,
      `    'bestiary.title': 'Bestiarium ${ap} Gegner & Beute',`,
      `    'bestiary.intro': 'Alle erfassten Kreaturen: LP, Beute und Fundorte. Mit dem Community-Wiki abgeglichen.',`,
      `    'bestiary.name': 'Kreatur',`,
      `    'bestiary.kind': 'Typ',`,
      `    'bestiary.hp': 'LP',`,
      `    'bestiary.drops': 'Beute',`,
      `    'bestiary.notes': 'Notizen',`,
      `    'bestiary.hostile': 'Feindlich',`,
      `    'bestiary.passive': 'Passiv',`,
      `    'bestiary.group.anywhere': '\u00dcberall (Raids & Nacht)',`,
      `    'bestiary.group.plains': 'Ebenen',`,
      `    'bestiary.group.forest': 'Wald',`,
      `    'bestiary.group.desert': 'W\u00fcste',`,
      `    'bestiary.group.volcano': 'Vulkan',`,
      `    'worship.title': 'Kult-Techtree',`,
      `    'worship.intro': 'Gib Kult-Punkte aus Altar-Opfern aus, um Knoten Stufe f\u00fcr Stufe freizuschalten.',`,
      `    'worship.tier': 'Stufe',`,
      `    'worship.node': 'Knoten',`,
      `    'worship.effect': 'Effekt',`,
      `    'worship.cost': 'Kosten',`,
      `    'worship.prereq': 'Ben\u00f6tigt',`,
      `    'worship.wp': 'KP',`,
      `    'minerva.quests.title': 'Minervas Quest-Kette',`,
      `    'minerva.quests.intro': 'Minerva hat keinen Kult-Tree ${ap} ihre Kraft kehrt durch Quests zur\u00fcck. Opfere diese Gegenst\u00e4nde am Altar.',`,
      `    'minerva.quests.offer': 'Am Altar opfern',`,
      `    'minerva.quests.reward': 'Belohnung',`,
    ],
  },
  es: {
    anchor: "escrito y mantenido al d\u00eda por un peque\u00f1o grupo de gobernadores",
    keys: [
      `    'nav.bestiary': 'Bestiario',`,
      `    'bestiary.title': 'Bestiario ${ap} Enemigos y botines',`,
      `    'bestiary.intro': 'Todas las criaturas registradas: PV, botines y lugares de aparici\u00f3n. Cotejado con la wiki comunitaria.',`,
      `    'bestiary.name': 'Criatura',`,
      `    'bestiary.kind': 'Tipo',`,
      `    'bestiary.hp': 'PV',`,
      `    'bestiary.drops': 'Botines',`,
      `    'bestiary.notes': 'Notas',`,
      `    'bestiary.hostile': 'Hostil',`,
      `    'bestiary.passive': 'Pasiva',`,
      `    'bestiary.group.anywhere': 'En cualquier lugar (incursiones y noche)',`,
      `    'bestiary.group.plains': 'Llanuras',`,
      `    'bestiary.group.forest': 'Bosques',`,
      `    'bestiary.group.desert': 'Desierto',`,
      `    'bestiary.group.volcano': 'Volc\u00e1n',`,
      `    'worship.title': '\u00c1rbol de culto',`,
      `    'worship.intro': 'Gasta los Puntos de Culto ganados con ofrendas en el altar para desbloquear nodos, nivel a nivel.',`,
      `    'worship.tier': 'Nivel',`,
      `    'worship.node': 'Nodo',`,
      `    'worship.effect': 'Efecto',`,
      `    'worship.cost': 'Coste',`,
      `    'worship.prereq': 'Requiere',`,
      `    'worship.wp': 'PC',`,
      `    'minerva.quests.title': 'Cadena de misiones de Minerva',`,
      `    'minerva.quests.intro': 'Minerva no tiene \u00e1rbol de culto ${ap} su poder vuelve con misiones. Ofrece estos objetos en tu Altar.',`,
      `    'minerva.quests.offer': 'Ofrecer en el altar',`,
      `    'minerva.quests.reward': 'Recompensa',`,
    ],
  },
  it: {
    anchor: "scritto e tenuto aggiornato da un piccolo gruppo di governatori",
    keys: [
      `    'nav.bestiary': 'Bestiario',`,
      `    'bestiary.title': 'Bestiario ${ap} Nemici e bottini',`,
      `    'bestiary.intro': 'Tutte le creature censite: PV, bottini e luoghi di comparsa. Dati verificati con la wiki della community.',`,
      `    'bestiary.name': 'Creatura',`,
      `    'bestiary.kind': 'Tipo',`,
      `    'bestiary.hp': 'PV',`,
      `    'bestiary.drops': 'Bottini',`,
      `    'bestiary.notes': 'Note',`,
      `    'bestiary.hostile': 'Ostile',`,
      `    'bestiary.passive': 'Passiva',`,
      `    'bestiary.group.anywhere': 'Ovunque (raid e notte)',`,
      `    'bestiary.group.plains': 'Pianure',`,
      `    'bestiary.group.forest': 'Foreste',`,
      `    'bestiary.group.desert': 'Deserto',`,
      `    'bestiary.group.volcano': 'Vulcano',`,
      `    'worship.title': 'Albero di culto',`,
      `    'worship.intro': 'Spendi i Punti di Culto ottenuti con le offerte all${ap}altare per sbloccare i nodi, livello per livello.',`,
      `    'worship.tier': 'Livello',`,
      `    'worship.node': 'Nodo',`,
      `    'worship.effect': 'Effetto',`,
      `    'worship.cost': 'Costo',`,
      `    'worship.prereq': 'Richiede',`,
      `    'worship.wp': 'PC',`,
      `    'minerva.quests.title': 'Catena di quest di Minerva',`,
      `    'minerva.quests.intro': 'Minerva non ha un albero di culto ${ap} il suo potere torna con le quest. Offri questi oggetti al tuo Altare.',`,
      `    'minerva.quests.offer': 'Offrire all${ap}altare',`,
      `    'minerva.quests.reward': 'Ricompensa',`,
    ],
  },
};

let done = 0;
for (const [lang, { anchor, keys }] of Object.entries(blocks)) {
  const idx = raw.indexOf(anchor);
  if (idx === -1) { console.log(`MISS ${lang}`); continue; }
  // find the end of that footer.built line
  const lineEnd = raw.indexOf('\n', idx);
  if (lineEnd === -1) { console.log(`MISS-EOL ${lang}`); continue; }
  raw = raw.slice(0, lineEnd + 1) + keys.join('\n') + '\n' + raw.slice(lineEnd + 1);
  done++;
  console.log(`OK ${lang}`);
}

fs.writeFileSync(path, raw, 'utf8');
console.log(`inserted blocks: ${done}/5`);
